# Data Configuration
data:
  # Input data settings
  input:
    file_path: "../../Data.xlsx"  # Relative to pipeline root
    file_type: "excel"
    
  # Signal data configuration
  signals:
    ppg:
      start_column: 6
      end_column: 206
      length: 200
      sampling_rate: 125
      
    ecg:
      start_column: 206
      end_column: 406
      length: 200
      sampling_rate: 125
  
  # Target variables
  targets:
    sbp_column: 3
    dbp_column: 4
    
  # Patient information
  patient_id_column: 0
  ptt_column: 5
  
  # Data validation rules
  validation:
    # Physiological ranges for quality check
    sbp_range: [80, 250]  # mmHg
    dbp_range: [40, 150]  # mmHg
    
    # Signal quality thresholds
    signal_quality:
      min_amplitude_ratio: 0.1  # Min signal amplitude vs noise
      max_saturation_percent: 5  # Max % of saturated samples
      min_dynamic_range: 0.05    # Min signal dynamic range
      
    # Missing data thresholds
    max_missing_percent: 10  # Max % missing values per signal
    
    # Outlier detection
    outlier_method: 'iqr'  # 'iqr', 'zscore', 'isolation_forest'
    outlier_threshold: 3.0
    
# Data preprocessing
preprocessing:
  # Signal filtering
  filtering:
    enabled: true
    type: 'butterworth'
    order: 4
    lowpass_cutoff: 10   # Hz
    highpass_cutoff: 0.5 # Hz
    
  # Artifact removal
  artifact_removal:
    enabled: true
    methods: ['motion_artifacts', 'baseline_wander', 'powerline_interference']
    
  # Normalization per signal
  signal_normalization:
    enabled: true
    method: 'z_score'  # 'z_score', 'min_max', 'robust'
    
  # Data augmentation (for training)
  augmentation:
    enabled: false
    methods: ['time_warping', 'magnitude_warping', 'noise_injection']
    augmentation_factor: 1.5  # Multiply dataset size by this factor

# Data splitting
splitting:
  strategy: 'patient_aware'  # 'random', 'patient_aware', 'temporal'
  test_size: 0.2
  validation_size: 0.1
  random_state: 42
  
  # Patient-aware splitting
  patient_grouping:
    min_patients_per_fold: 5
    stratify_by_bp_range: true
    
# Data quality monitoring
quality_monitoring:
  enabled: true
  
  # Statistical drift detection
  drift_detection:
    enabled: true
    reference_period: 'training'
    methods: ['ks_test', 'chi2_test', 'psi']
    
  # Signal quality metrics
  signal_metrics:
    - 'signal_to_noise_ratio'
    - 'peak_detection_quality'
    - 'morphology_consistency'
    - 'temporal_consistency'
    
# Feature extraction configuration
feature_extraction:
  # Time domain features
  time_domain:
    enabled: true
    features:
      - 'mean'
      - 'std'
      - 'min'
      - 'max'
      - 'range'
      - 'skewness'
      - 'kurtosis'
      - 'rms'
      - 'variance'
      - 'median'
      - 'percentiles'  # 25th, 75th
      
  # Frequency domain features
  frequency_domain:
    enabled: true
    features:
      - 'power_spectral_density'
      - 'spectral_centroid'
      - 'spectral_bandwidth'
      - 'spectral_rolloff'
      - 'spectral_flatness'
    frequency_bands:
      - name: 'very_low'
        range: [0, 0.5]
      - name: 'low'
        range: [0.5, 1.5]
      - name: 'mid'
        range: [1.5, 4.0]
      - name: 'high'
        range: [4.0, 10.0]
        
  # Morphological features
  morphological:
    enabled: true
    features:
      - 'peak_count'
      - 'peak_amplitudes'
      - 'peak_intervals'
      - 'rise_time'
      - 'fall_time'
      - 'pulse_width'
      - 'area_under_curve'
      
  # Cross-signal features
  cross_signal:
    enabled: true
    features:
      - 'cross_correlation'
      - 'mutual_information'
      - 'coherence'
      - 'phase_difference'
      - 'pulse_arrival_time'
